name=MIDI-controlled-leslie
version=0.1.0
author=Henrik Horpedal
maintainer=Henrik Horpedal hhorpedal@gmail.com
sentence=Leslie speaker.
paragraph= .
category=Other
url=.
architectures=*
includes=footswitch.h
