name=MIDI-controlled-leslie
version=0.1.0
author=Henrik Horpedal
maintainer=Henrik Horpedal hhorpedal@gmail.com
sentence=Leslie speaker.
paragraph= .
category=Other
url=.
architectures=*
depends=ACAN2517FD (=2.1.16),Moteus (=1.1.1),MIDI Library (=5.0.2),Adafruit TinyUSB Library (=3.7.7)
